name: CI Pipeline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest flake8 black

        - name: Lint with flake8
          run: flake8 src tests

        - name: Format with black
          run: black src tests

        - name: Run tests
          run: |
            pytest tests/